# Generated by Django 4.2.25 on 2025-11-02 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('industry', models.CharField(help_text='Ej: Tecnología, Finanzas, Salud, etc.', max_length=100, verbose_name='Nicho/Área')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Color principal de la marca (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido (ej: #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Color secundario de la marca (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido (ej: #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color secundario')),
                ('accent_color', models.CharField(default='#60A5FA', help_text='Color de acento de la marca (hex)', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido (ej: #FF5733)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color de acento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
