# Generated by Django 4.2.25 on 2025-11-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('event_code', models.CharField(help_text='Código único para acceder al evento', max_length=20, unique=True, verbose_name='Código del evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Lugar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.company', verbose_name='Empresa organizadora')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
