# Generated by Django 4.2.25 on 2025-11-03 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accent_color',
            field=models.CharField(default='#60A5FA', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color de acento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100, verbose_name='Nicho/Área'),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color primario'),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', max_length=7, validators=[django.core.validators.RegexValidator(message='Ingresa un color hexadecimal válido', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color secundario'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código del evento'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/', verbose_name='Foto de perfil')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('company_name', models.CharField(max_length=200, verbose_name='Empresa')),
                ('bio', models.TextField(blank=True, verbose_name='Descripción')),
                ('interests', models.JSONField(default=list, verbose_name='Intereses')),
                ('linkedin_url', models.URLField(blank=True, max_length=500, verbose_name='LinkedIn')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('access_code', models.CharField(max_length=12, unique=True, verbose_name='Código de acceso')),
                ('code_verified', models.BooleanField(default=False, verbose_name='Código verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='api.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
