# Generated by Django 4.2.25 on 2025-11-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_accent_color_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='18:00', verbose_name='Hora final'),
        ),
        migrations.AddField(
            model_name='event',
            name='networking_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Horas de networking'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Hora de inicio'),
        ),
    ]
