# Generated by Django 4.2.25 on 2025-11-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_end_time_event_networking_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=5, verbose_name='Hora del slot')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_slots', to='api.profile', verbose_name='Perfil receptor')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_requests', to='api.profile', verbose_name='Perfil solicitante')),
            ],
            options={
                'verbose_name': 'Slot de Networking',
                'verbose_name_plural': 'Slots de Networking',
                'ordering': ['time_slot', '-created_at'],
                'unique_together': {('profile', 'time_slot')},
            },
        ),
    ]
