# Generated by Django 4.2.25 on 2025-11-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_networkingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, verbose_name='Horarios disponibles'),
        ),
        migrations.AlterField(
            model_name='networkingslot',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_slots_received', to='api.profile', verbose_name='Perfil receptor'),
        ),
        migrations.AlterField(
            model_name='networkingslot',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_slots_sent', to='api.profile', verbose_name='Perfil solicitante'),
        ),
    ]
